# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HelmAppChecker < Formula
  desc "Check Helm release versions against latest available from Artifact Hub and GitHub"
  homepage "https://github.com/7adityaraj"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/7adityaraj/homebrew-tap/releases/download/v1.0.0/helm-app-checker_darwin_amd64.tar.gz"
      sha256 "9a3c4a346bb13c43574b143da38b9bade56355b31ab87bdb710cd669dd7926eb"

      define_method(:install) do
        bin.install "helm-app-checker"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/7adityaraj/homebrew-tap/releases/download/v1.0.0/helm-app-checker_darwin_arm64.tar.gz"
      sha256 "5da4c69fdbc0630531a7b385b8901aea4a64e9e828532bb0d4aa1a2cb997dd80"

      define_method(:install) do
        bin.install "helm-app-checker"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/7adityaraj/homebrew-tap/releases/download/v1.0.0/helm-app-checker_linux_amd64.tar.gz"
      sha256 "61bf1b7a8d90f85f6619661d5afcd97302690999b31560c73c9fc6c6fd7ea927"
      define_method(:install) do
        bin.install "helm-app-checker"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/7adityaraj/homebrew-tap/releases/download/v1.0.0/helm-app-checker_linux_arm64.tar.gz"
      sha256 "7a69e7bf80cc043d808a7928b870413c39a390c349d3d6de4a69c20d1e607abc"
      define_method(:install) do
        bin.install "helm-app-checker"
      end
    end
  end
end
