# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HelmAppChecker < Formula
  desc "Check Helm release versions against latest available from Artifact Hub and GitHub"
  homepage "https://github.com/7adityaraj"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/7adityaraj/homebrew-tap/releases/download/v1.0.0/helm-app-checker_darwin_amd64.tar.gz"
      sha256 "55f8c9777d3ba478f177d05a6900b7306dd7cdc5fcce11c9d63aad1371d75ba3"

      define_method(:install) do
        bin.install "helm-app-checker"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/7adityaraj/homebrew-tap/releases/download/v1.0.0/helm-app-checker_darwin_arm64.tar.gz"
      sha256 "3d53b475a7807ffd8f34173cc508e1b2598ddcfb26c3765879ede3798b7b9721"

      define_method(:install) do
        bin.install "helm-app-checker"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/7adityaraj/homebrew-tap/releases/download/v1.0.0/helm-app-checker_linux_amd64.tar.gz"
      sha256 "07027a1c2f373453ecab2df0e6a341cce8ecf6ec9222cba556476190e1ec7048"
      define_method(:install) do
        bin.install "helm-app-checker"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/7adityaraj/homebrew-tap/releases/download/v1.0.0/helm-app-checker_linux_arm64.tar.gz"
      sha256 "3e0496b1babe749871b0e05f178e58390731dc967948fb232794575f56409f05"
      define_method(:install) do
        bin.install "helm-app-checker"
      end
    end
  end
end
